# Generated by Django 4.0.3 on 2022-05-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_account_balance_account_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
