# Generated by Django 4.0.3 on 2022-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_remove_account_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='text',
            new_name='title',
        ),
    ]
