# Generated by Django 4.0.3 on 2022-05-12 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bank_app', '0005_alter_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('customer_rank', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('GOLD', 'Gold')], default='basic', max_length=6)),
            ],
        ),
    ]
