# Generated by Django 4.0.3 on 2022-05-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_store_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'get_latest_by': 'pk'},
        ),
    ]
