# Generated by Django 4.0.3 on 2022-05-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_alter_account_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='transactions',
            new_name='transaction',
        ),
    ]
