# Generated by Django 4.0.3 on 2022-05-23 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_ledger_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='totp_identity',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
