# Generated by Django 4.0.3 on 2022-05-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0015_customer_totp_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('transfer_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text', models.TextField(default='text')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_app.store')),
            ],
        ),
    ]
