# Generated by Django 4.0.3 on 2022-05-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0016_bank_externalledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Loan account', 'Loan Account'), ('Debit card', 'Debit Card'), ('Credit card', 'Credit Card'), ('Savings account', 'Savings Account')], default='Savings account', max_length=20),
        ),
    ]
