# Generated by Django 4.0.5 on 2022-06-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0019_stockholdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholdings',
            name='bought_at',
            field=models.IntegerField(),
        ),
    ]
