# Generated by Django 4.0.3 on 2022-06-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0020_stockholdings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='ExternalLedger',
        ),
    ]
