# Generated by Django 4.0.5 on 2022-06-08 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_app', '0023_alter_ledger_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoHoldings',
            fields=[
                ('holding_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=5)),
                ('shares', models.IntegerField()),
                ('bought_at', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
