# Generated by Django 4.0.5 on 2022-06-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0024_cryptoholdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoholdings',
            name='shares',
            field=models.FloatField(),
        ),
    ]
