# Generated by Django 4.0.3 on 2022-05-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
